MovieConstants = {
  MOVIES_RECEIVED: "MOVIES_RECEIVED",
  MOVIE_RECEIVED: "MOVIE_RECEIVED",
  CREATE_FAIL: "MOVIE_CREATE_FAIL",
  MOVIE_CREATED: "MOVIE_CREATED",
  MOVIE_UPDATED: "MOVIE_UPDATED",
  EDIT_FAIL: "MOVIE_EDIT_FAIL",
  MOVIE_DESTROYED: "MOVIE_DESTROYED",
  DELETE_FAIL: "MOVIE_DELETE_FAIL"
};

module.exports = MovieConstants;
