MovieConstants = {
  MOVIES_RECEIVED: "MOVIES_RECEIVED",
  MOVIE_RECEIVED: "MOVIE_RECEIVED",
  MOVIE_CREATED: "MOVIE_CREATED",
  MOVIE_DESTROYED: "MOVIE_DESTROYED"
};

module.exports = MovieConstants;
