MovieConstants = {
  MOVIES_RECEIVED: "MOVIES_RECEIVED",
  MOVIE_RECEIVED: "MOVIE_RECEIVED",
  CREATE_FAIL: 'CREATE_FAIL',
  MOVIE_CREATED: "MOVIE_CREATED",
  MOVIE_UPDATED: "MOVIE_UPDATED",
  EDIT_FAIL: "EDIT_FAIL",
  MOVIE_DESTROYED: "MOVIE_DESTROYED",
  DELETE_FAIL: "DELETE_FAIL"
};

module.exports = MovieConstants;
