ReviewConstants = {
  REVIEWS_RECEIVED: "REVIEWS_RECEIVED",
  REVIEW_RECEIVED: "REVIEW_RECEIVED",
  // CREATE_FAIL: "REVIEW_CREATE_FAIL",
  REVIEW_CREATED: "REVIEW_CREATED",
  REVIEW_UPDATED: "REVIEW_UPDATED",
  // EDIT_FAIL: "REVIEW_EDIT_FAIL",
  REVIEW_DESTROYED: "REVIEW_DESTROYED",
  // DELETE_FAIL: "REVIEW_DELETE_FAIL"
};

module.exports = ReviewConstants;
