ReviewConstants = {
  REVIEWS_RECEIVED: "REVIEWS_RECEIVED",
  REVIEW_RECEIVED: "REVIEW_RECEIVED",
  FORM_FALSE: "FORM_FALSE",
  REVIEW_CREATED: "REVIEW_CREATED",
  REVIEW_UPDATED: "REVIEW_UPDATED",
  REVIEW_DESTROYED: "REVIEW_DESTROYED",
};

module.exports = ReviewConstants;
