UserConstants = {
  SIGNING_UP: "SIGNING_UP",
  GO_BACK: "GO_BACK",
  FOUND_USER: "FOUND_USER",
  RECEIVED_USER: "RECEIVED_USER",
  LOGGING_IN: "LOGGING_IN",
  SESSION_CREATED: "SESSION_CREATED",
  LOGIN_REQUIRED: "LOGIN_REQUIRED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
};

module.exports = UserConstants;
