UserConstants = {
  RECEIVED_USER: "RECEIVED_USER",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
  SIGNING_UP: "SIGNING_UP",
  LOGGING_IN: "LOGGING_IN",
};

module.exports = UserConstants;
