UserConstants = {
  SIGNING_UP: "SIGNING_UP",
  RECEIVED_USER: "RECEIVED_USER",
  NO_SUCH_USER: "NO_SUCH_USER",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  LOGGING_IN: "LOGGING_IN",
  SESSION_CREATED: "SESSION_CREATED",
  LOGIN_REQUIRED: "LOGIN_REQUIRED",
  SESSION_DESTROYED: "SESSION_DESTROYED",
};

module.exports = UserConstants;
