
movies = [
  { title: 'Fight Club', release_date: Date.new(1999, 10, 15), year: 1999,
    director: 'David Fincher',
    actors: 'Edward Norton, Brad Pitt, Helena Bonham Carter, Meat Loaf',
    image_url: "http://cdn2-www.comingsoon.net/assets/uploads/1970/01/file_611196_fight-club-curb-2-640x320.jpg",
    plot: "An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soap maker, forming an underground fight club that evolves into something much, much more..."
  },
  { title: 'Pulp Fiction', release_date: Date.new(1994, 10, 14), year: 1994,
    director: 'Quentin Tarantino',
    actors: 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis',
    image_url: "http://images.mentalfloss.com/sites/default/files/pulpfiction.jpeg",
    plot: "The lives of two mob hit men, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption."
  },
  { title: "The Dark Knight", year: 2008,
    director: "Christopher Nolan",
    actors: "Christian Bale, Heath Ledger, Aaron Eckhart",
    image_url: "http://wallpaperswide.com/download/batman_the_dark_knight_3-wallpaper-960x640.jpg",
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice."
  },
  { title: "The Big Lebowski", year: 1998,
    director: "Joel Coen",
    actors: "Jeff Bridges, John Goodman, Julianne Moore, Steve Buscemi",
    image_url: "http://cdn.collider.com/wp-content/uploads/the-big-lebowski-movie-image-01.jpg",
    plot: "'The Dude' Lebowski, mistaken for a millionaire Lebowski, seeks restitution for his ruined rug and enlists his bowling buddies to help get it."
  },
  { title: "The Shawshank Redemption", year: 1994,
    director: "Frank Darabont",
    actors: "Tim Robbins, Morgan Freeman, Bob Gunton",
    image_url: "http://i.telegraph.co.uk/multimedia/archive/02772/shawshank1_2772806b.jpg",
    plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency."
  },
  { title: "The Godfather", year: 1972,
    director: "Francis Ford Coppola",
    actors: "Marlon Brando, Al Pacino, James Caan",
    image_url: "http://cdn.crushable.com/files/2011/03/thegodfather.jpg",
    plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son."
  },
  { title: "Finding Nemo", year: 2003,
    director: "Andrew Stanton",
    actors: "Albert Brooks, Ellen DeGeneres",
    image_url: "http://img4.wikia.nocookie.net/__cb20130801230959/disney/images/d/d4/Finding_Nemo(7).jpg",
    plot: "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home."
  },
  { title: "Harry Potter and the Sorcerer's Stone", year: 2001,
    director: "Chris Columbus",
    actors: "Daniel Radcliffe, Emma Watson, Rupert Grint, Richard Harris, Maggie Smith",
    image_url: "http://images.contentful.com/7h71s48744nc/2bPKBoWupiim0SiOg4Y6eA/103c011afb362cda5a10a0c7964c378c/harry-potter-and-the-sorcerers-stone.jpg",
    plot: "Rescued from the outrageous neglect of his aunt and uncle, a young boy with a great destiny proves his worth while attending Hogwarts School of Witchcraft and Wizardry."
  },
  { title: "The Lord of the Rings: Return of the King", year: 2003,
    director: "Peter Jackson",
    actors: "Elijah Wood, Viggo Mortensen, Ian McKellen",
    image_url: "http://www.filmhdwallpapers.com/files/movie/The-Lord-of-the-Rings-The-Return-of-the-King-HD-Wallpapers.jpg",
    plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring."
  },
  { title: "Beauty and the Beast", year: 1991,
    director: "Gary Trousdale",
    actors: "Paige O'Hara, Robby Benson, Jesse Corti",
    image_url: "http://cdn.collider.com/wp-content/uploads/beauty-and-the-beast-disney.jpg",
    plot: "Belle, whose father is imprisoned by the Beast, offers herself instead, unaware her captor to be an enchanted prince."
  },
  { title: "The Wizard of Oz", year: 1939,
    director: "Victor Fleming",
    actors: "Judy Garland, Frank Morgan, Ray Bolger",
    image_url: "http://www.tamswitmark.com/wp-content/uploads/2013/09/Wizard-of-Oz-RSC-and-MUNI1-541x346.jpg",
    plot: "Dorothy Gale is swept away to a magical land in a tornado and embarks on a quest to see the Wizard who can help her return home."
  },
  { title: "Avatar", year: 2009,
    director: "James Cameron",
    actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver",
    image_url: "http://assets1.ignimgs.com/2014/11/26/avatar-1280cjpg-44d49c_1280w.jpg",
    plot: "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home."
  },
  { title: "The Avengers", year: 2012,
    director: "Joss Whedon",
    actors: "Robert Downey Jr., Chris Evans, Scarlett Johansson, Chris Hemsworth, Mark Ruffalo, Jeremy Renner",
    image_url: "http://screenrant.com/wp-content/uploads/The-Avengers-Movie-Roster-Concept-Art.jpg",
    plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity."
  },
  { title: "The Incredibles", year: 2004,
    director: "Brad Bird",
    actors: "Craig T. Nelson, Samuel L. Jackson, Holly Hunter",
    image_url: "http://www.insidethemagic.net/wp-content/uploads/2014/03/incredibles.jpg",
    plot: "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world."
  },
  { title: "Willy Wonka and the Chocolate Factory", year: 1971,
    director: "Mel Stuart",
    actors: "Gene Wilder, Jack Albertson, Peter Ostrum",
    image_url: "https://www.relix.com/images/sized/images/uploads/willy-wonka--the-chocolate-factory-4fea54fa7c6ab-760x428.jpg",
    plot: "A poor boy wins the opportunity to tour the most eccentric and wonderful candy factory of all."
  }
]
# { title: "", year ,
#   director: "",
#   actors: "",
#   image_url: "",
#   plot: ""
# }
movies.each { |movie| Movie.create(movie) }

users = [
  { username: "Guest", password: "password" },
  { username: "Amazon", password: "password" },
  { username: "Twitter", password: "password" },
  { username: "Ben", password: "password" },
  { username: "Cody", password: "password" },
  { username: "The Dude", password: "password" },
  { username: "Ghost", password: "password" },
  { username: "Neck Beard", password: "password" },
  { username: "Kyle", password: "password" },
]

users.each { |user| User.create(user) }


# :title, :body, :author_name, :movie_id, :user_id
reviews = [
  { title: "Shhh",
    body: "I'm not supposed to talk about it",
    author_name: "Twitter", movie_id: 1, user_id: 3 },
  { title: "Who would have imagined.",
    body: "A conversation about hamburgers leads to violence.",
    author_name: "Twitter", movie_id: 2, user_id: 3 },
  { title: "What a shame.",
    body: "Miserable billionaire terrorizes mentally ill man.",
    author_name: "Twitter", movie_id: 3, user_id: 3 },
  { title: "Weird",
    body: "Noseless guy has an unhealthy obsession with a teenage boy.",
    author_name: "Twitter", movie_id: 8, user_id: 3 },
  { title: "Typical",
    body: "White child is told he is special, then he goes to private school.",
    author_name: "Twitter", movie_id: 8, user_id: 3 },
  { title: "Sad, really",
    body: "Man takes a vacation to destroy a family heirloom.",
    author_name: "Twitter", movie_id: 9, user_id: 3 },
  { title: "Psychologically gripping",
    body: "Love in the time of stockholm syndrome with anthropomorphic household items.",
    author_name: "Twitter", movie_id: 10, user_id: 3 },
  { title: "Kind of funny",
    body: "Impressionable teenage girl from Kansas tries acid for the first time.",
    author_name: "Twitter", movie_id: 11, user_id: 3 },
  { title: "Boring",
    body: "Hitch hikers with self-esteem issues get lost in the woods and meet a televangelist who is a fraud.",
    author_name: "Twitter", movie_id: 11, user_id: 3 },
  { title: "It's been done before",
    body: "Pocahontas with blue people.",
    author_name: "Twitter", movie_id: 12, user_id: 3 },
  { title: "A family story",
    body: "Adopted child's older brother will not let him hold the hammer.",
    author_name: "Twitter", movie_id: 13, user_id: 3 },
  { title: "At least it is animated",
    body: "Man's midlife crisis endangers his family and an entire city.",
    author_name: "Twitter", movie_id: 14, user_id: 3 },
  { title: "Almost a horror movie",
    body: "A drug crazed lunatic slowly kills children in front of their parents, one by one.",
    author_name: "Twitter", movie_id: 15, user_id: 3 },
  { title: "Sounds like a drama",
    body: "The story of a handicapped boy, Nemo, who's mother and siblings were brutally murdered by a serial killer. On his first day of school, he is abducted by a masked man and is held prisoner in a dentist's office. The story chronicles his father's journey to find him with the help of a mentally disabled woman and his attempts at escape. ...as portrayed by animated fish.",
    author_name: "Kyle", movie_id: 7, user_id: 9 },
  { title: "One Star",
    body: "My husband loves this movie. I don't know why.",
    author_name: "Amazon", movie_id: 4, user_id: 2 },
  { title: "Had to turn it off after they portrayed Police as violent criminals that hurt the innocent! Not in my USA!!!!!",
    body: "Happy late groundhogz day folkz! LOL! I love me a good movie here and there... and ever since I got fired from McDonalds for sleeping in the bathroom my FIRST and only entire shift LMAOZ! I decided that I would watch movies until I got my next job. Anywho... on to Samuel L Jackson and Dan Akroid... they have never really been good actors to begin with and this movie doesnt seem to have a plot at all. The plot and actors seem very one-dimensional and lack any sort of emotion or acting talent... I bet the script was written with people who were drunk off Sparkling Apple Cider LOLZ... (it only takes me 2 sips and im a lil tipsy myself).... and the entire jail/criminal justice thing has been overplayed ever since day 1. Comon.. give me a break folkz... in what country do people get sentenced to life or beat up in prison?? NOT in the USA :)) we are free here. Police here are scrutinized for what! they are GOOD hearted people and would never shot or hurt an innocent man :)... Anywho.. i didn't really have the stomach to watch this after it showed a man get beaten by police... something that would NEVER happen in real life! The plot in itself seems very fictional... They should have hired a better director and definitely a better cast... why didnt they cast good actors like iCarly? Jason Biggs? Or even Carrot Top!?? For good Hollywood.....stick with Jersey Shore, The Kardashians, and anything with Bob Saggot. For a good flick. stick with Britney Spears 'Crossroads' , Lindsay Lohans 'The Parent Trap' , and that one Christmas Movie that Adam Sandler burpz and fartz in LOL!",
    author_name: "Amazon", movie_id: 5, user_id: 2 },
  { title: "Amazing movie, no translation for a majority of the italian",
    body: "Get a different version, very frustrating lack of translation including the scene in the restaurant where they speak italian for several minutes.",
    author_name: "Amazon", movie_id: 6, user_id: 2 },
  { title: "It's Just",
    body: "Cultural appropriation in space.",
    author_name: "Twitter", movie_id: 12, user_id: 3 },
  { title: "Takes a while",
    body: "Group spends 9 hours returning jewelry.",
    author_name: "Twitter", movie_id: 9, user_id: 3 },
  { title: "Spoiler Alert",
    body: "A guy is two guys.",
    author_name: "Twitter", movie_id: 1, user_id: 3 },
  { title: "Insanity is:",
    body: "An Evil bald guy tried to kill the same kid for 7 years and still didn't.",
    author_name: "Twitter", movie_id: 8, user_id: 3 },
  { title: "Long Con",
    body: "An old man pretends to be bed-ridden for years until he gets a chance at some free chocolate.",
    author_name: "Twitter", movie_id: 15, user_id: 3 },
  { title: "Newsworthy",
    body: "A girl and a small dog kill the first person they see in a strange land, then meet 3 other misfits to kill again.",
    author_name: "Twitter", movie_id: 11, user_id: 3 },
  { title: "Endless struggle",
    body: "Short people fight with tall people over a lousy piece of jewelry. Then take it to be destroyed.",
    author_name: "Twitter", movie_id: 9, user_id: 3 },
  { title: "Group therapy",
    body: "A man gets stuck in a rut and decides to start a club but doesn't let anyone talk about it.",
    author_name: "Twitter", movie_id: 1, user_id: 3 },
  { title: "Extra! Extra!",
    body: "Nerd girl and monster saved by tupperware.",
    author_name: "Twitter", movie_id: 10, user_id: 3 },
  { title: "50 Shades of fur",
    body: "A pretty, bookish girl becomes an outcast in her own town when she realizes she's a furry.",
    author_name: "Twitter", movie_id: 10, user_id: 3 },
  { title: "It was a nice quilt",
    body: "Racist man given monetary gift by well-dressed man after being inconvenienced for an afternoon.",
    author_name: "Twitter", movie_id: 2, user_id: 3 },
  { title: "How do you define a villain?",
    body: "Genius egalitarian gets beat into a pulp by the culturally elite he only wishes to emulate.",
    author_name: "Twitter", movie_id: 14, user_id: 3 },
  { title: "Quaint",
    body: "Co-workers go to breakfast and talk through vocational crisis, help a couple start new life.",
    author_name: "Twitter", movie_id: 2, user_id: 3 },
  { title: "Chick flick",
    body: "Imaginary friend with 6 pack beats up guys and makes soap.",
    author_name: "Twitter", movie_id: 1, user_id: 3 },
  { title: "Know your limits",
    body: "Man who knows deep down that he will never be Brad Pitt creates global financial chaos.",
    author_name: "Twitter", movie_id: 1, user_id: 3 },
  { title: "Birthday party gone wrong",
    body: "A clown wants to show everyone a big magic trick,but is stopped by a creepy man in a rubber suit.",
    author_name: "Twitter", movie_id: 3, user_id: 3 },
  { title: "That's one way to recover",
    body: "A man who was molested by bats during his childhood sets out to catch a villain that loves his make-up.",
    author_name: "Twitter", movie_id: 3, user_id: 3 },
  { title: "Way to go!",
    body: "First ginger kid ever to make two friends at school.",
    author_name: "Twitter", movie_id: 8, user_id: 3 },
  { title: "Fish out of water",
    body: "A young English boy gets shanghaied into an education system stuck in the 15th century.",
    author_name: "Twitter", movie_id: 8, user_id: 3 },
  { title: "Friend-zoned",
    body: "Boy spends 7 years being a third wheel.",
    author_name: "Twitter", movie_id: 8, user_id: 3 },
  { title: "Mistaken Identity",
    body: "A perpetually exasperated plagiarist is mistaken for a zen icon and master criminal.",
    author_name: "Twitter", movie_id: 4, user_id: 3 },
  { title: "American Abroad",
    body: "American invades foreign land, kills local leadership, struggles to find exit strategy.",
    author_name: "Twitter", movie_id: 11, user_id: 3 },
  { title: "Like the happening",
    body: "Everybody on a planet is controlled by a telepathic tree which orders them to kill all humans.",
    author_name: "Twitter", movie_id: 12, user_id: 3 },
  { title: "Fitness regimen",
    body: "Short guy walks a lot.",
    author_name: "Twitter", movie_id: 9, user_id: 3 },
  { title: "Horrific",
    body: "Convicted murderer lures old black man to isolated Mexican beach.",
    author_name: "Twitter", movie_id: 5, user_id: 3 },
  { title: "Slow construction",
    body: "Man takes 20 years to make a hole in a wall.",
    author_name: "Twitter", movie_id: 5, user_id: 3 },
  { title: "What would you do?",
    body: "Man goes for poo swim because he's over getting touched.",
    author_name: "Twitter", movie_id: 5, user_id: 3 },
  { title: "Secretive",
    body: "Son pretends to dislike violence, but secretly likes shooting people in the face.",
    author_name: "Twitter", movie_id: 6, user_id: 3 },
  { title: "The American Dream",
    body: "An Italian American gets rich by specializing in word of mouth marketing for his Olive Oil business.",
    author_name: "Twitter", movie_id: 6, user_id: 3 },
  { title: "Family drama",
    body: "Once upon a time there was a king and he had 3 sons.",
    author_name: "Twitter", movie_id: 6, user_id: 3 },
  { title: "Barely notable",
    body: "Australian man catches fish.",
    author_name: "Twitter", movie_id: 7, user_id: 3 },
  { title: "Tough punishment",
    body: "Boy is kidnapped and kept as a gift after assaulting an innocent boat.",
    author_name: "Twitter", movie_id: 7, user_id: 3 },
  { title: "Poor parenting",
    body: "Overprotective dad won't let his child live his life, and hires an investigator to track him down.",
    author_name: "Twitter", movie_id: 7, user_id: 3 },
  { title: "Interesting combination",
    body: "Dances with Wolves meets The Smurfs.",
    author_name: "Twitter", movie_id: 12, user_id: 3 },
  { title: "Cruel idea",
    body: "A disabled man is teased with a working body.",
    author_name: "Twitter", movie_id: 12, user_id: 3 },
  { title: "Fashion fail",
    body: "Alien thinks helmet is cool. No one else agrees.",
    author_name: "Twitter", movie_id: 13, user_id: 3 },
  { title: "Build a wall already.",
    body: "Cosplay icons destroy New York while trying to stop a group of immigrants from coming to the US.",
    author_name: "Twitter", movie_id: 13, user_id: 3 },
  { title: "I know a good place.",
    body: "A group of heroes ban together to commit genocide on an alien race and then celebrate with shawarma.",
    author_name: "Twitter", movie_id: 13, user_id: 3 },
  { title: "Still entertaining.",
    body: "A group of mutants assemble to listen to Robert Downey Jr. quips.",
    author_name: "Twitter", movie_id: 13, user_id: 3 },
  { title: "I know it looks bad,",
    body: "Wife goes through husbands stuff, gets wrong end of stick and causes problems.",
    author_name: "Twitter", movie_id: 14, user_id: 3 },
  { title: "It's a small field",
    body: "The only good Disney movie where one or both of the parents aren't dead.",
    author_name: "Twitter", movie_id: 14, user_id: 3 },
  { title: "High drama",
    body: "In a family full of secrets a father's past mistake comes back to cause much destruction & turmoil.",
    author_name: "Twitter", movie_id: 14, user_id: 3 },
  { title: "What's not to like?",
    body: "People didn't like superheroes until some of them saved the world- then they did.",
    author_name: "Twitter", movie_id: 14, user_id: 3 },
  { title: "Great press",
    body: "Astute businessman holds a contest to boost sales.",
    author_name: "Twitter", movie_id: 15, user_id: 3 },
  { title: "Seemed like a good idea at the time.",
    body: "Five Kids break the #1 rule and take candy from a stranger.",
    author_name: "Twitter", movie_id: 15, user_id: 3 },
  { title: "Know your opposition.",
    body: "Young boy exposes factory owner for having small slaves working 24 hrs a day and leverages the information for chocolate.",
    author_name: "Twitter", movie_id: 15, user_id: 3 },
]
reviews.each { |review| Review.create(review) }
            # {PF: "A conversation about hamburgers leads to violence"},
            # {FC: "I'm not supposed to talk about it"},
            # {DK: "Miserable billionaire terrorizes mentally ill man."},
            # {HP: "Noseless guy has an unhealthy obsession with a teenage boy."},
            # {HP: "White child is told he is special, then he goes to private school."},
            # {LotR: "Man takes a vacation to destroy a family heirloom."},
            # {BatB: "Love in the time of stockholm syndrome."},
            # {WoO: "Impressionable teenage girl from Kansas tries acid for the first time."},
            # {WoO: "Hitch hikers with self-esteem issues get lost in the woods and meet a televangelist who is a fraud."},
            # {Avatar: "Pocahontas with blue people."},
            # {Avengers: "Adopted child's older brother will not let him hold the hammer."},
            # {Incredibles: "Man's midlife crisis endangers his family and an entire city."},
            # {WWatCF: "A drug crazed lunatic slowly kills children in front of their parents, one by one."}
#           ]
# (:value, :voter_id, :user_id, :review_id)
votes = [
  { value: 1, voter_id: 2, user_id: 3, review_id: 1 }
]
4.upto(9) do |voter_id|
  1.upto(63) do |review_id|
    if review_id % voter_id == 0
      value = -1
    else
      value = 1
    end
    votes << { value: value, voter_id: voter_id, user_id: 3, review_id: review_id }
  end
end
votes.each { |vote| Vote.create(vote) }

# directors= [
#   { name: 'David Fincher' },
#   { name: 'Quentin Tarantino' }
# ]
#
# actors = [
#   { name: 'Edward Norton'},
#   { name: 'Brad Pitt'},
#   { name: 'Helena Bonham Carter'},
#   { name: 'Meat Loaf'},
#   { name: 'John Travolta'},
#   { name: 'Samuel L. Jackson'},
#   { name: 'Uma Thurman'},
#   { name: 'Bruce Willis'}
# ]
#
# castings = [
#   { movie_id: 1, actor_id: 1, order: 1 },
#   { movie_id: 1, actor_id: 2, order: 2 },
#   { movie_id: 1, actor_id: 3, order: 3 },
#   { movie_id: 1, actor_id: 4, order: 4 },
#   { movie_id: 2, actor_id: 5, order: 1 },
#   { movie_id: 2, actor_id: 6, order: 2 },
#   { movie_id: 2, actor_id: 7, order: 3 },
#   { movie_id: 2, actor_id: 8, order: 4 },
# ]
#
#
